module.exports = {
  INFO:             'INFO',
  ADMIN_NOTICE:     'ADMIN_NOTICE',
  RESULT_PUBLISHED: 'RESULT_PUBLISHED',
  PROMOTION:        'PROMOTION',
  GRADUATION:       'GRADUATION',
  SESSION_STARTED:  'SESSION_STARTED',
  SESSION_ADVANCE:  'SESSION_ADVANCE',
  SYSTEM_NOTICE:    'SYSTEM_NOTICE'
};
